#!/usr/bin/env python

import paho.mqtt.client
import mqtt_config
import time
import xmltodict
import json
import serial

#Test in test/, check http://spacehub.somakeit.org.uk
#for advice choosing a topic for production
TOPIC = "somakeit/space/power/usage"
SERIAL_PORT = "/dev/ttyUSB0"
BAUD_RATE = 57600

#Connect to a broker
mqtt = paho.mqtt.client.Client(client_id=mqtt_config.client_id, clean_session=True)
#Use real root certificates
mqtt.tls_set(("/etc/ssl/certs/ca-certificates.crt"))
mqtt.username_pw_set(mqtt_config.user_name, mqtt_config.password)
mqtt.loop_start()
while True:
    try:
        mqtt.connect(mqtt_config.server, port=mqtt_config.port)
        break
    except Exception as e:
        print "failed to connecct: " + str(e)
        time.sleep(60)
        print "retrying.."

#open the serial port
ser = serial.Serial(SERIAL_PORT, BAUD_RATE)

while True:
    timestamp = int(time.time())

    #get the next line from the meter
    line = ser.readline()

    #convrt to sane data if we can
    try:
        data = xmltodict.parse(line)
    except Exception:
        continue

    data.update({"timestamp": timestamp})

    message = json.dumps(data)

    mqtt.publish(TOPIC, payload=message, qos=0, retain=True)

